### ISSUE TITLE
error when creating arena 

### ISSUE THREAD

**Issue by ghost** [iZeaoGamer/SurvivalGames-Pocketmine#3]
using the the latest phar from the releases section.

```
Notice: Undefined variable: SWname in phar:///storage/emulated/0/PocketMine/plugins/SurvivalGames_v1.0.0.phar/src/Zeao/commands.php on line 148
[00:41:58] [Server thread/INFO]: mote teleported to t1
[00:41:58] [Server thread/INFO]: Unloading level "v2"
[00:42:00] [Server thread/INFO]: Preparing level "v2"
[00:42:00] [Server thread/INFO]: [TapToDo] Reloading blocks due to level v2 loaded...
[00:42:00] [Server thread/CRITICAL]: Unhandled exception executing command 'sg create test 2 30 300' in sg: Class Zeao\SGarena not found
[00:42:00] [Server thread/CRITICAL]: ClassNotFoundException: "Class Zeao\SGarena not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
```

**Comment by ZPlayzMCPE** [comment]
Which update did you get? Did you get V1.0.0 or V1.0.1? Be more specific.

**Comment by ghost** [comment]
1.0.1

**Comment by iZeaoGamer** [comment]
It should now be fixed. Download the latest phar here.
https://poggit.pmmp.io/r/8793/SurvivalGames.phar
Let me know on the results. And tell me whether it's fixed or not. Thank you. I will leave this open for 7 days. If you don't reply back, It'll automatically be closed. Thank you.

**Comment by iZeaoGamer** [comment]
If it doesn't fix, try downloading the latest release from the Github releases tab. Thank you. Closing in 7 days.

**Comment by ghost** [comment]
I got this error after creating the arena : 
```Server thread/CRITICAL]: Unhandled exception executing command 'sg create test 4 30 300' in sg: Class Zeao\arena not found 25.07 19:02:41 [Server] INFO [Server thread/CRITICAL]: ClassNotFoundException: "Class Zeao\arena not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144``` 

it was creating a backup of the arena then it said an error has occurred... etc and the arena wasn't saved

**Comment by ghost** [comment]
Using ver 1.0.0.2 from the releases section in github ^

**Comment by ghost** [comment]
Happened in the poggit version aswell ^

**Comment by ghost** [comment]
@iZeaoGamer

**Comment by iZeaoGamer** [comment]
Hi, I am fully back working on this project again. I am glad to say that this issue should now be resolved and fixed. If you experience anymore issues, then please open a new issue. Thank you.

**Comment by ghost** [comment]
i closed my server 4 months ago lol
